# Generated by Django 5.2.8 on 2026-02-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0015_reporteplataforma_unidad_tiempo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(help_text='Nombre del sistema (ej: IDEAL CLOUD, EFLUENTE SMA, CO2 Y TURBIDEZ)', max_length=200)),
                ('monto_mensual_uf', models.DecimalField(decimal_places=2, help_text='Costo mensual en UF', max_digits=10)),
                ('monto_mensual_clp', models.DecimalField(decimal_places=2, help_text='Costo mensual en CLP', max_digits=15)),
                ('costo_diario_uf', models.DecimalField(decimal_places=6, help_text='Costo por día (24h) en UF', max_digits=10)),
                ('costo_diario_clp', models.DecimalField(decimal_places=2, help_text='Costo por día (24h) en CLP', max_digits=15)),
                ('costo_hora_uf', models.DecimalField(blank=True, decimal_places=6, help_text='Costo por hora en UF', max_digits=10, null=True)),
                ('costo_hora_clp', models.DecimalField(blank=True, decimal_places=2, help_text='Costo por hora en CLP', max_digits=15, null=True)),
                ('plazo_contrato', models.CharField(default='36 MESES', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('cantidad_sensores', models.IntegerField(blank=True, help_text='Cantidad de sensores en este sistema', null=True)),
                ('costo_total_uf', models.DecimalField(decimal_places=2, help_text='Costo total del contrato en UF', max_digits=10)),
                ('costo_total_clp', models.DecimalField(decimal_places=2, help_text='Costo total del contrato en CLP', max_digits=15)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_sistemas', to='incidencias.centro')),
            ],
            options={
                'verbose_name': 'Costo de Sistema',
                'verbose_name_plural': 'Costos de Sistemas',
                'ordering': ['centro', 'sistema'],
                'unique_together': {('centro', 'sistema')},
            },
        ),
        migrations.CreateModel(
            name='RegistroInactividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio de la falla')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha y hora de fin de la falla (dejar vacío si aún está activa)', null=True)),
                ('duracion_horas', models.DecimalField(blank=True, decimal_places=2, help_text='Duración total en horas', max_digits=10, null=True)),
                ('duracion_dias', models.DecimalField(blank=True, decimal_places=2, help_text='Duración total en días', max_digits=10, null=True)),
                ('perdida_uf', models.DecimalField(blank=True, decimal_places=4, help_text='Pérdida económica en UF', max_digits=10, null=True)),
                ('perdida_clp', models.DecimalField(blank=True, decimal_places=2, help_text='Pérdida económica en CLP', max_digits=15, null=True)),
                ('motivo', models.CharField(choices=[('SENSOR_APAGADO', 'Sensor apagado'), ('SENSOR_MAL_ESTADO', 'Sensor en mal estado'), ('NO_SUBE_DATOS', 'No sube datos a la plataforma'), ('FALLA_COMUNICACION', 'Falla de comunicación'), ('MANTENIMIENTO', 'En mantenimiento'), ('OTRO', 'Otro motivo')], max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la falla')),
                ('contacto_proveedor', models.BooleanField(default=False, help_text='¿Se contactó al proveedor?')),
                ('fecha_contacto', models.DateTimeField(blank=True, null=True)),
                ('respuesta_proveedor', models.TextField(blank=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('incluir_en_reporte', models.BooleanField(default=True, help_text='Incluir en reporte de descuentos')),
                ('observaciones_reporte', models.TextField(blank=True, help_text='Observaciones adicionales para el reporte')),
                ('responsable', models.CharField(help_text='Persona que registra la incidencia', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('costo_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_inactividad', to='incidencias.costosistema')),
                ('sensor', models.ForeignKey(blank=True, help_text='Sensor específico afectado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_inactividad', to='incidencias.sensorconfig')),
            ],
            options={
                'verbose_name': 'Registro de Inactividad',
                'verbose_name_plural': 'Registros de Inactividad',
                'ordering': ['-fecha_inicio', '-creado_en'],
            },
        ),
    ]
