# Generated by Django 5.2.8 on 2026-02-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0016_costosistema_registroinactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroinactividad',
            name='valor_uf_usado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de la UF en CLP al momento del cálculo', max_digits=10, null=True),
        ),
    ]
